// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    id: "1",
    base_url: "https://template.postman-echo.com"
  }
});

export default function() {
  postman[Request]({
    name: "Get data",
    id: "26b98281-163f-41a5-a31d-68c57f8d2d65",
    method: "GET",
    address: "{{base_url}}/info?id=1",
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Post data",
    id: "f405d3ad-5afa-43a6-89e2-9f5eb16df5ea",
    method: "POST",
    address: "{{base_url}}/info",
    data: '{\n\t"name": "Add your name in the body"\n}',
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("Successful POST request", function() {
        pm.expect(pm.response.code).to.be.oneOf([200, 201]);
      });
    }
  });

  postman[Request]({
    name: "Update data",
    id: "740a21e2-0acb-43a7-a712-e44a019bf140",
    method: "PUT",
    address: "{{base_url}}/info?id=1",
    data: '{\n\t"name": "Add your name in the body"\n}',
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("Successful PUT request", function() {
        pm.expect(pm.response.code).to.be.oneOf([200, 201, 204]);
      });
    }
  });

  postman[Request]({
    name: "Delete data",
    id: "96f6d751-b9a7-4a1e-b34f-725679ddfb83",
    method: "DELETE",
    address: "{{base_url}}/info?id=1",
    post(response) {
      pm.test("Successful DELETE request", function() {
        pm.expect(pm.response.code).to.be.oneOf([200, 202, 204]);
      });
    }
  });
}
