apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: my-first-testrun
spec:
  script:
    configMap:
      name: my-test
      file: script.js
  parallelism: 2 # Run 2 k6 instances in parallel
  arguments: "--vus 5 --duration 60s --out experimental-prometheus-rw"
  runner:
    image: grafana/k6:0.47.0
    imagePullPolicy: IfNotPresent
    env:
      - name: K6_INSECURE_SKIP_TLS_VERIFY
        value: "true"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://kind-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
